steps: 60000
dataset:
  repo_id: dageorge1111/v140_coffee_pod_train_no_quaternions
  image_transforms:
    enable: false
    max_num_transforms: 3
    random_order: false
    tfs:
      brightness:
        weight: 1.0
        type: ColorJitter
        kwargs:
          brightness: [0.8, 1.2]
      contrast:
        weight: 1.0
        type: ColorJitter
        kwargs:
          contrast: [0.8, 1.2]
      saturation:
        weight: 1.0
        type: ColorJitter
        kwargs:
          saturation: [0.5, 1.5]
      hue:
        weight: 1.0
        type: ColorJitter
        kwargs:
          hue: [-0.05, 0.05]
      sharpness:
        weight: 1.0
        type: SharpnessJitter
        kwargs:
          sharpness: [0.5, 1.5]

policy:
  type: act
  push_to_hub: false
  n_obs_steps: 1
  chunk_size: 100
  n_action_steps: 100
  normalization_mapping:
    VISUAL: MEAN_STD
    STATE: MEAN_STD
    ACTION: MEAN_STD
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  replace_final_stride_with_dilation: false
  pre_norm: true
  dim_model: 512
  n_heads: 8
  dim_feedforward: 3200
  feedforward_activation: relu
  n_encoder_layers: 6
  n_decoder_layers: 1
  use_vae: true
  latent_dim: 32
  n_vae_encoder_layers: 1
  temporal_ensemble_coeff: null
  dropout: 0.1
  kl_weight: 10.0

optimizer:
  type: adamw
  lr: 1.0e-5
  weight_decay: 1.0e-4
  grad_clip_norm: 10.0
  betas: [0.9, 0.999]
  eps: 1.0e-8

scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 500
  num_decay_steps: 100000
  peak_lr: 1.0e-5
  decay_lr: 1.0e-6

eval:
  n_episodes: 50
  batch_size: 50
  use_async_envs: false

wandb:
  enable: true
  project: coffee_pod_act
  disable_artifact: true
  entity: null
  notes: null
  run_id: null
  mode: online

output_dir: ./v141
job_name: v141
resume: false
seed: 1000
num_workers: 4
batch_size: 8
eval_freq: 20000
log_freq: 200
save_checkpoint: true
save_freq: 20000
